# This file is used for local environment
services:

  backend:
    image: tin:latest
    depends_on:
      - db
    ports:
      - 8001:8001
    environment:
      - APP_ENV=dev
      - APP_BASE_URL=0.0.0.0
      - PORT=8001
      - DATABASE_URL=postgres://gandalf:SpeakFriendAndEnter@db/tin

  db:
    image: docker.io/postgres:17.6
    ports:
      - 5432:5432
    volumes:
      # Use `:Z` in SELinux-enabled disro.
      - ./_volumes/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: gandalf
      POSTGRES_PASSWORD: SpeakFriendAndEnter
      POSTGRES_DB: tin
